### PR TITLE
Feature/carousel

### PR DESCRIPTION
**Pull request by AmyPegramBBD**

### CODE REVIEW

**Review by nikitaabrey — COMMENTED** [review]
Looks amazing Amy! :)

Just wanted to check, when I run it with "node app" it is not putting in the correct CSS. Is that fine? Otherwise it looks and works perfectly, if I just open the html file. For the tablet view could we perhaps make the carousel a bit bigger?

**Comment by AmyPegramBBD** [comment]
> Looks amazing Amy! :)
> 
> Just wanted to check, when I run it with "node app" it is not putting in the correct CSS. Is that fine? Otherwise it looks and works perfectly, if I just open the html file. For the tablet view could we perhaps make the carousel a bit bigger?

Oooh I see the issue with that! Let me fix it quickly! I'll also make the carousel bigger, is that for when the text is underneath?

**Comment by nikitaabrey** [comment]
> > Looks amazing Amy! :)
> > Just wanted to check, when I run it with "node app" it is not putting in the correct CSS. Is that fine? Otherwise it looks and works perfectly, if I just open the html file. For the tablet view could we perhaps make the carousel a bit bigger?
> 
> Oooh I see the issue with that! Let me fix it quickly! I'll also make the carousel bigger, is that for when the text is underneath?

When I put the size on iPad it makes the carousel a little block in the top left corner. On the phone and laptop it looks good though, so it isn't a really big deal if it will be a lot of effort right now.

**Comment by AmyPegramBBD** [comment]
> > > Looks amazing Amy! :)
> > > Just wanted to check, when I run it with "node app" it is not putting in the correct CSS. Is that fine? Otherwise it looks and works perfectly, if I just open the html file. For the tablet view could we perhaps make the carousel a bit bigger?
> > 
> > 
> > Oooh I see the issue with that! Let me fix it quickly! I'll also make the carousel bigger, is that for when the text is underneath?
> 
> When I put the size on iPad it makes the carousel a little block in the top left corner. On the phone and laptop it looks good though, so it isn't a really big deal if it will be a lot of effort right now.

Fixed! The most recent commit should all work also with node now

**Comment by nikitaabrey** [comment]
> > > > Looks amazing Amy! :)
> > > > Just wanted to check, when I run it with "node app" it is not putting in the correct CSS. Is that fine? Otherwise it looks and works perfectly, if I just open the html file. For the tablet view could we perhaps make the carousel a bit bigger?
> > > 
> > > 
> > > Oooh I see the issue with that! Let me fix it quickly! I'll also make the carousel bigger, is that for when the text is underneath?
> > 
> > 
> > When I put the size on iPad it makes the carousel a little block in the top left corner. On the phone and laptop it looks good though, so it isn't a really big deal if it will be a lot of effort right now.
> 
> Fixed! The most recent commit should all work also with node now

Works perfectly!! Thank you so much.

**Review by nikitaabrey — APPROVED** [review]

**Pull request merged**
