### PR TITLE
Adopt page x2

### PR DESCRIPTION
**Pull request by Natasha-Khumalo-BBD**
Collapsing box is open to further styling and also the button hover colour or any styles to make it more poppy.
Let us know if there's anything else :)

### CODE REVIEW

**Review by nikitaabrey — COMMENTED** [review]
Looks amazing Natasha! Thank you for all the work you did on the screens! 

I just wanted to bring up a few things I noticed. 
- The one is that I see the "Find out more about me" button now highlights yellow when you hover over it and underlines. I feel like the underline is enough feedback to the user, I am happy with both just want to check if everyone is happy with that?
- Also for the "Find out more about me" should it not be redirecting to the individual dog page instead of listing the information in the cards? Or is that what we decided the functionality would be?

**Comment by Natasha-Khumalo-BBD** [comment]
> 
Thank you, you also did great work on page :) !

Oh yeah you have point, I can remove the hover colour 👍 
I actually wasnt sure what should be inside the "Find out more about me" so i put those two bullets as a placeholder.

Now that you've mentioned it, I'll make changes so it redirects to the other page Andrew made.

**Comment by nikitaabrey** [comment]
> * t

We can see which one everyone prefers first as well, before changing it. 
Awesome, thank you! :)

**Comment by Natasha-Khumalo-BBD** [comment]
> 

Alright cool :)

**Comment by anelbas** [comment]
This page looks really good, well done!

I agree with Nikita the hover effect can be limited to the underline text-decoration. I would also say that when the screen reaches tablet size there should be two cards displayed next to each other instead of just one or it should maybe be centralized?

Also, the navbar wasn't called correctly so it is not showing up. Try changing the path of the script and css file to "../navbar/navbar.css "or .js

**Comment by nikitaabrey** [comment]
> 

I will make these changes quick.

**Comment by nikitaabrey** [comment]
> This page looks really good, well done!
> 
> I agree with Nikita the hover effect can be limited to the underline text-decoration. I would also say that when the screen reaches tablet size there should be two cards displayed next to each other instead of just one or it should maybe be centralized?
> 
> Also, the navbar wasn't called correctly so it is not showing up. Try changing the path of the script and css file to "../navbar/navbar.css "or .js

These changes have been made, only the button functionality left to update.

**Review by AmyPegramBBD — APPROVED** [review]

**Pull request closed without merging**
