### PR TITLE
Feat: Individual dog page content

### PR DESCRIPTION
**Pull request by AndrewBB-BBD**
Note: The image in here is a placeholder image. A carousel will go there.

**Visual "testing":**

- Please check out the content layout and let me know if you're happy. 
- Please let me know of any colour, text or other styling changes.
- Resize the screen and check whether you're happy with the media query layout changes. The layout changes when the screen width is <768px.

**Functional testing:**
- Hide/show details button -> when hovering on the button, it should be underlined and your cursor should change to a pointer. Clicking it will either hide or show additional details. The text should toggle between "More details" and "Hide details"

NB: Please check all the semantic elements / tags! 

Let me know of any content changes as well :) 

Thank you!!

### CODE REVIEW

**Comment by anelbas** [comment]
First of - this looks great!
- The resizing of the page is great
- The button that shows/hides details works beautifully (love the child friendly one)
- Your spacing and color use is gorgeous.
- Very happy with your semantic tags

The only two things I can comment on is that
1. There is no hover effect on the button (on the other pages the button goes darker and the cursor turns into a pointer)
2. When you go into mobile mode it would look better if the picture was centered but that's more like a nice-to-have

**Comment by AndrewBB-BBD** [comment]
> First of - this looks great!
> 
> * The resizing of the page is great
> * The button that shows/hides details works beautifully (love the child friendly one)
> * Your spacing and color use is gorgeous.
> * Very happy with your semantic tags
> 
> The only two things I can comment on is that
> 
> 1. There is no hover effect on the button (on the other pages the button goes darker and the cursor turns into a pointer)
> 2. When you go into mobile mode it would look better if the picture was centered but that's more like a nice-to-have

@anelbas Thank you for this review! I've never felt so flattered in a PR review before :') 
1. I'll do the button things and let you know when I've pushed.
2. I left the image stuff for Amy because the carousel will be there, but may just do the centering anyway in the meanwhile.

**Review by nikitaabrey — COMMENTED** [review]
I agree with Anel it looks amazing! I will approve once the changes have been pushed :)

**Comment by AndrewBB-BBD** [comment]
@nikitasmal @anelbas PR updated! Test and let me know what you think :)

**Review by nikitaabrey — APPROVED** [review]

**Comment by nikitaabrey** [comment]
> @nikitasmal @anelbas PR updated! Test and let me know what you think :)

Perfect! Thank you so much for all your guys work on this! <3
We are going to have the coolest app ever! ;)

**Review by anelbas — APPROVED** [review]
Looks great Andrew, thanks for making the changes.

**Review by Natasha-Khumalo-BBD — COMMENTED** [review]
All Looks good !
- Love the slideup of the collapsing functionality :)

**Pull request merged**
